name: Generate Docs in /docs Folder

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-docs.txt
          pip install -e ".[gui]"

      - name: Generate docs with pdoc into /docs
        run: |
          pdoc star_shine -o docs

      - name: Commit and push updated docs
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/
          git diff --quiet && git diff --staged --quiet || git commit -m "Update docs [skip ci]"
          git push
